# Pandas
* Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series

In [57]:
import pandas as pd
import numpy as np

In [58]:
#Generate a DF from numpy array
df= pd.DataFrame(np.arange(20).reshape(5,4),index=['row1','row2','row3','row4','row5'], columns=['a', 'b', 'c', 'd'])

In [59]:
df

a   b   c   d
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

# Slicing elements in a Dataframe
* loc ... accessing row 
* iloc... accesing both rows and columns

In [60]:
df.loc["row1"]

a    0
b    1
c    2
d    3
Name: row1, dtype: int32

In [61]:
type(df.loc["row1"])

pandas.core.series.Series

In [62]:
df.loc["row1"][0:2]

a    0
b    1
Name: row1, dtype: int32

In [63]:
df.iloc[1:3,0:4]

a  b   c   d
row2  4  5   6   7
row3  8  9  10  11

In [64]:
type(df.iloc[1:3,0:4])

pandas.core.frame.DataFrame

# Convert Dataframe into an Array
* When you use the .values method it forms an array

In [65]:
df.iloc[0:,0:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [66]:
type(df.iloc[0:,0:].values)

numpy.ndarray

In [67]:
arr=df.iloc[0:,0:].values[0,1]=-1000

In [68]:
df  # I made a change in nummpy array and reflected after in the numpy array

a     b   c   d
row1   0 -1000   2   3
row2   4     5   6   7
row3   8     9  10  11
row4  12    13  14  15
row5  16    17  18  19

In [69]:
df.iloc[0:,0:].values > 4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
df[df.iloc[0:,0:].values > 4]

a   b   c   d
row2   4   5   6   7
row2   4   5   6   7
row2   4   5   6   7
row3   8   9  10  11
row3   8   9  10  11
row3   8   9  10  11
row3   8   9  10  11
row4  12  13  14  15
row4  12  13  14  15
row4  12  13  14  15
row4  12  13  14  15
row5  16  17  18  19
row5  16  17  18  19
row5  16  17  18  19
row5  16  17  18  19

In [71]:
df['a'].value_counts()  # unique value of attribultes or elements

12    1
4     1
16    1
8     1
0     1
Name: a, dtype: int64

In [72]:
df.isnull().sum()

a    0
b    0
c    0
d    0
dtype: int64

In [73]:
df['a'].unique()

array([ 0,  4,  8, 12, 16])

In [74]:
df

a     b   c   d
row1   0 -1000   2   3
row2   4     5   6   7
row3   8     9  10  11
row4  12    13  14  15
row5  16    17  18  19

In [75]:
df.columns=[["aa","bb","cc","dd"]]

In [76]:
df

aa    bb  cc  dd
row1   0 -1000   2   3
row2   4     5   6   7
row3   8     9  10  11
row4  12    13  14  15
row5  16    17  18  19

# Reading Data

In [47]:
data=pd.read_csv('benz.csv')

In [48]:
data

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 378 columns]

In [77]:
data.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]